config/routes.rb
Rails.application.routes.draw do
  get '/' => 'categories#index'
  get '/categories/:category_id' => 'categories#show', as: 'category'
  get '/categories/:category_id/items/new' => 'items#new'
  get '/categories/:category_id/items/:id' => 'items#show', as: 'item'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :categories do
    resources :items
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true

  belongs_to :category
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  has_many :items
  def password
    @password ||= BCrypt::Password.new(hashed_password)
  end

  def password=(password)
    @password = BCrypt::Password.create(password)
    self.hashed_password = @password
  end


  def self.authenticate(email, password)
    user = self.find_by(email: email)
    if user != nil
      user.password == password
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:edit, :update, :show, :destroy]
  def index
    @categories = Category.all
  end

  def show
  end

  private

  def find_category
    @category = Category.find(params[:category_id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item_and_category, only: [:edit, :update, :show, :destroy]

  def new
    @category = Category.find(params[:category_id])
    @item = Item.new
  end

  def create
    @category = Category.find(params[:category_id])
    @item = Item.new(item_params)
    if @item.save
      redirect_to category_item_path
    else
      @errors = @item.errors.full_messages[0..-2]
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update_attributes(item_params)
      redirect_to category_item_path
    else
      @errors = @item.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to category_path(@category)
    else
      @errors = @item.errors.full_messages
      render :edit
    end
  end

  private

  def find_item_and_category
    @category = Category.find(params[:category_id])
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price, :description)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user && User.authenticate(session_params[:email], session_params[:password])
      session[:user_id] = user.id
      redirect_to categories_path
    else
        @errors = ["Invalid login!"]
        render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/'
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/'
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
      params.require(:user).permit(:user_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper

  def user_logged_in
    @user ||= User.find_by(id: session[:user_id])
  end

end

app/views/categories/index.html.erb
<div class="categories">
  <h3>Choose a category</h3>
  <ul class="category-list">
    <%@categories.each do |category| %>
      <li> <%= link_to("#{category.name}", category_path(category))%></li>
    <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<h2 class="category">Category: <%=@category.name%></h2>
<div class="add-item"><%=link_to("+ Add a new item", new_category_item_path)%></div>
<div class="all-items">
  <% @category.items.each do |item| %>
    <ul>
      <li class="items">
        <span class="price">$<%=item.price%></span><span class="name"><%= link_to("#{item.name}", [@category, item])%></span>
        <span class="updated-at"><%=item.updated_at.strftime("%I:%M:%S%p %b %d, %Y")%></span>
      </li>
    </ul>
  <% end %>
</div>

app/views/items/_form.html.erb
<%= form_for [@category, @item] do |f| %>
  Name: <%= f.text_field :name %><br>
  Price: <%= f.text_field :price %><br>
  Description: <%= f.text_area :description %><br>

  <%= f.submit %>
<% end %>
<% if @errors %>
  <% @errors.each do |error|%>
    <p class="error"><%=error%></p>
    <%end%>
<% end %>

app/views/items/edit.html.erb
<%= render :partial => 'form' %>

app/views/items/new.html.erb
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<h2>$<%=@item.price%> <%=@item.name%></h2>
<%=link_to("Edit", edit_category_item_path(@category, @item))%>
<%=link_to("Delete", category_item_path(@category, @item), method: :delete)%>
<p><%=@item.description%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sarah's List</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="headers">
    <% if user_logged_in %>
      <li class="header">
        <%=link_to("Logout", logout_path, :method => :delete)%>
      </li>
    <% else %>
      <li class="header">
        <%=link_to("Login", '/login')%>
      </li>
      <li class="header">
        <%=link_to("Sign Up", '/users/new')%>
      </li>
    <% end %>
    <li class="header">
      <%=link_to("Home", categories_path)%>
    </li>
  </nav>
  <h1 class="sarahs-list">Sarah's List</h1>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  Username: <%= f.text_field :user_name%> <br>
  Email: <%= f.text_field :email %> <br>
  Password: <%= f.password_field :password %> <br>
  <%= f.submit "Sign Up!"%>
<% end %>
<% if @errors %>
  <% @errors.each do |error|%>
    <p class="error"><%=error%></p>
    <%end%>
<% end %>